# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mediapipe/calculators/tflite/tflite_inference_calculator.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mediapipe.framework import calculator_pb2 as mediapipe_dot_framework_dot_calculator__pb2
mediapipe_dot_framework_dot_calculator__options__pb2 = mediapipe_dot_framework_dot_calculator__pb2.mediapipe_dot_framework_dot_calculator__options__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mediapipe/calculators/tflite/tflite_inference_calculator.proto',
  package='mediapipe',
  syntax='proto2',
  serialized_pb=_b('\n>mediapipe/calculators/tflite/tflite_inference_calculator.proto\x12\tmediapipe\x1a$mediapipe/framework/calculator.proto\"\xfb\x08\n TfLiteInferenceCalculatorOptions\x12\x12\n\nmodel_path\x18\x01 \x01(\t\x12\x1a\n\x07use_gpu\x18\x02 \x01(\x08:\x05\x66\x61lseB\x02\x18\x01\x12\x1c\n\tuse_nnapi\x18\x03 \x01(\x08:\x05\x66\x61lseB\x02\x18\x01\x12\x1a\n\x0e\x63pu_num_thread\x18\x04 \x01(\x05:\x02-1\x12\x46\n\x08\x64\x65legate\x18\x05 \x01(\x0b\x32\x34.mediapipe.TfLiteInferenceCalculatorOptions.Delegate\x1a\xc9\x06\n\x08\x44\x65legate\x12M\n\x06tflite\x18\x01 \x01(\x0b\x32;.mediapipe.TfLiteInferenceCalculatorOptions.Delegate.TfLiteH\x00\x12G\n\x03gpu\x18\x02 \x01(\x0b\x32\x38.mediapipe.TfLiteInferenceCalculatorOptions.Delegate.GpuH\x00\x12K\n\x05nnapi\x18\x03 \x01(\x0b\x32:.mediapipe.TfLiteInferenceCalculatorOptions.Delegate.NnapiH\x00\x12O\n\x07xnnpack\x18\x04 \x01(\x0b\x32<.mediapipe.TfLiteInferenceCalculatorOptions.Delegate.XnnpackH\x00\x1a\x08\n\x06TfLite\x1a\x9b\x03\n\x03Gpu\x12#\n\x14use_advanced_gpu_api\x18\x01 \x01(\x08:\x05\x66\x61lse\x12N\n\x03\x61pi\x18\x04 \x01(\x0e\x32<.mediapipe.TfLiteInferenceCalculatorOptions.Delegate.Gpu.Api:\x03\x41NY\x12\"\n\x14\x61llow_precision_loss\x18\x03 \x01(\x08:\x04true\x12\x1a\n\x12\x63\x61\x63hed_kernel_path\x18\x02 \x01(\t\x12g\n\x05usage\x18\x05 \x01(\x0e\x32G.mediapipe.TfLiteInferenceCalculatorOptions.Delegate.Gpu.InferenceUsage:\x0fSUSTAINED_SPEED\"&\n\x03\x41pi\x12\x07\n\x03\x41NY\x10\x00\x12\n\n\x06OPENGL\x10\x01\x12\n\n\x06OPENCL\x10\x02\"N\n\x0eInferenceUsage\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x16\n\x12\x46\x41ST_SINGLE_ANSWER\x10\x01\x12\x13\n\x0fSUSTAINED_SPEED\x10\x02\x1a/\n\x05Nnapi\x12\x11\n\tcache_dir\x18\x01 \x01(\t\x12\x13\n\x0bmodel_token\x18\x02 \x01(\t\x1a\"\n\x07Xnnpack\x12\x17\n\x0bnum_threads\x18\x01 \x01(\x05:\x02-1B\n\n\x08\x64\x65legate2Y\n\x03\x65xt\x12\x1c.mediapipe.CalculatorOptions\x18\xcd\x8f\xc2o \x01(\x0b\x32+.mediapipe.TfLiteInferenceCalculatorOptions')
  ,
  dependencies=[mediapipe_dot_framework_dot_calculator__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_TFLITEINFERENCECALCULATOROPTIONS_DELEGATE_GPU_API = _descriptor.EnumDescriptor(
  name='Api',
  full_name='mediapipe.TfLiteInferenceCalculatorOptions.Delegate.Gpu.Api',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ANY', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OPENGL', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OPENCL', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=957,
  serialized_end=995,
)
_sym_db.RegisterEnumDescriptor(_TFLITEINFERENCECALCULATOROPTIONS_DELEGATE_GPU_API)

_TFLITEINFERENCECALCULATOROPTIONS_DELEGATE_GPU_INFERENCEUSAGE = _descriptor.EnumDescriptor(
  name='InferenceUsage',
  full_name='mediapipe.TfLiteInferenceCalculatorOptions.Delegate.Gpu.InferenceUsage',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNSPECIFIED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAST_SINGLE_ANSWER', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUSTAINED_SPEED', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=997,
  serialized_end=1075,
)
_sym_db.RegisterEnumDescriptor(_TFLITEINFERENCECALCULATOROPTIONS_DELEGATE_GPU_INFERENCEUSAGE)


_TFLITEINFERENCECALCULATOROPTIONS_DELEGATE_TFLITE = _descriptor.Descriptor(
  name='TfLite',
  full_name='mediapipe.TfLiteInferenceCalculatorOptions.Delegate.TfLite',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=653,
  serialized_end=661,
)

_TFLITEINFERENCECALCULATOROPTIONS_DELEGATE_GPU = _descriptor.Descriptor(
  name='Gpu',
  full_name='mediapipe.TfLiteInferenceCalculatorOptions.Delegate.Gpu',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='use_advanced_gpu_api', full_name='mediapipe.TfLiteInferenceCalculatorOptions.Delegate.Gpu.use_advanced_gpu_api', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='api', full_name='mediapipe.TfLiteInferenceCalculatorOptions.Delegate.Gpu.api', index=1,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='allow_precision_loss', full_name='mediapipe.TfLiteInferenceCalculatorOptions.Delegate.Gpu.allow_precision_loss', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cached_kernel_path', full_name='mediapipe.TfLiteInferenceCalculatorOptions.Delegate.Gpu.cached_kernel_path', index=3,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='usage', full_name='mediapipe.TfLiteInferenceCalculatorOptions.Delegate.Gpu.usage', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=2,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TFLITEINFERENCECALCULATOROPTIONS_DELEGATE_GPU_API,
    _TFLITEINFERENCECALCULATOROPTIONS_DELEGATE_GPU_INFERENCEUSAGE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=664,
  serialized_end=1075,
)

_TFLITEINFERENCECALCULATOROPTIONS_DELEGATE_NNAPI = _descriptor.Descriptor(
  name='Nnapi',
  full_name='mediapipe.TfLiteInferenceCalculatorOptions.Delegate.Nnapi',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cache_dir', full_name='mediapipe.TfLiteInferenceCalculatorOptions.Delegate.Nnapi.cache_dir', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='model_token', full_name='mediapipe.TfLiteInferenceCalculatorOptions.Delegate.Nnapi.model_token', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1077,
  serialized_end=1124,
)

_TFLITEINFERENCECALCULATOROPTIONS_DELEGATE_XNNPACK = _descriptor.Descriptor(
  name='Xnnpack',
  full_name='mediapipe.TfLiteInferenceCalculatorOptions.Delegate.Xnnpack',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_threads', full_name='mediapipe.TfLiteInferenceCalculatorOptions.Delegate.Xnnpack.num_threads', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1126,
  serialized_end=1160,
)

_TFLITEINFERENCECALCULATOROPTIONS_DELEGATE = _descriptor.Descriptor(
  name='Delegate',
  full_name='mediapipe.TfLiteInferenceCalculatorOptions.Delegate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tflite', full_name='mediapipe.TfLiteInferenceCalculatorOptions.Delegate.tflite', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gpu', full_name='mediapipe.TfLiteInferenceCalculatorOptions.Delegate.gpu', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nnapi', full_name='mediapipe.TfLiteInferenceCalculatorOptions.Delegate.nnapi', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='xnnpack', full_name='mediapipe.TfLiteInferenceCalculatorOptions.Delegate.xnnpack', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_TFLITEINFERENCECALCULATOROPTIONS_DELEGATE_TFLITE, _TFLITEINFERENCECALCULATOROPTIONS_DELEGATE_GPU, _TFLITEINFERENCECALCULATOROPTIONS_DELEGATE_NNAPI, _TFLITEINFERENCECALCULATOROPTIONS_DELEGATE_XNNPACK, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='delegate', full_name='mediapipe.TfLiteInferenceCalculatorOptions.Delegate.delegate',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=331,
  serialized_end=1172,
)

_TFLITEINFERENCECALCULATOROPTIONS = _descriptor.Descriptor(
  name='TfLiteInferenceCalculatorOptions',
  full_name='mediapipe.TfLiteInferenceCalculatorOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_path', full_name='mediapipe.TfLiteInferenceCalculatorOptions.model_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='use_gpu', full_name='mediapipe.TfLiteInferenceCalculatorOptions.use_gpu', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\030\001'))),
    _descriptor.FieldDescriptor(
      name='use_nnapi', full_name='mediapipe.TfLiteInferenceCalculatorOptions.use_nnapi', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\030\001'))),
    _descriptor.FieldDescriptor(
      name='cpu_num_thread', full_name='mediapipe.TfLiteInferenceCalculatorOptions.cpu_num_thread', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='delegate', full_name='mediapipe.TfLiteInferenceCalculatorOptions.delegate', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='ext', full_name='mediapipe.TfLiteInferenceCalculatorOptions.ext', index=0,
      number=233867213, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[_TFLITEINFERENCECALCULATOROPTIONS_DELEGATE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=1263,
)

_TFLITEINFERENCECALCULATOROPTIONS_DELEGATE_TFLITE.containing_type = _TFLITEINFERENCECALCULATOROPTIONS_DELEGATE
_TFLITEINFERENCECALCULATOROPTIONS_DELEGATE_GPU.fields_by_name['api'].enum_type = _TFLITEINFERENCECALCULATOROPTIONS_DELEGATE_GPU_API
_TFLITEINFERENCECALCULATOROPTIONS_DELEGATE_GPU.fields_by_name['usage'].enum_type = _TFLITEINFERENCECALCULATOROPTIONS_DELEGATE_GPU_INFERENCEUSAGE
_TFLITEINFERENCECALCULATOROPTIONS_DELEGATE_GPU.containing_type = _TFLITEINFERENCECALCULATOROPTIONS_DELEGATE
_TFLITEINFERENCECALCULATOROPTIONS_DELEGATE_GPU_API.containing_type = _TFLITEINFERENCECALCULATOROPTIONS_DELEGATE_GPU
_TFLITEINFERENCECALCULATOROPTIONS_DELEGATE_GPU_INFERENCEUSAGE.containing_type = _TFLITEINFERENCECALCULATOROPTIONS_DELEGATE_GPU
_TFLITEINFERENCECALCULATOROPTIONS_DELEGATE_NNAPI.containing_type = _TFLITEINFERENCECALCULATOROPTIONS_DELEGATE
_TFLITEINFERENCECALCULATOROPTIONS_DELEGATE_XNNPACK.containing_type = _TFLITEINFERENCECALCULATOROPTIONS_DELEGATE
_TFLITEINFERENCECALCULATOROPTIONS_DELEGATE.fields_by_name['tflite'].message_type = _TFLITEINFERENCECALCULATOROPTIONS_DELEGATE_TFLITE
_TFLITEINFERENCECALCULATOROPTIONS_DELEGATE.fields_by_name['gpu'].message_type = _TFLITEINFERENCECALCULATOROPTIONS_DELEGATE_GPU
_TFLITEINFERENCECALCULATOROPTIONS_DELEGATE.fields_by_name['nnapi'].message_type = _TFLITEINFERENCECALCULATOROPTIONS_DELEGATE_NNAPI
_TFLITEINFERENCECALCULATOROPTIONS_DELEGATE.fields_by_name['xnnpack'].message_type = _TFLITEINFERENCECALCULATOROPTIONS_DELEGATE_XNNPACK
_TFLITEINFERENCECALCULATOROPTIONS_DELEGATE.containing_type = _TFLITEINFERENCECALCULATOROPTIONS
_TFLITEINFERENCECALCULATOROPTIONS_DELEGATE.oneofs_by_name['delegate'].fields.append(
  _TFLITEINFERENCECALCULATOROPTIONS_DELEGATE.fields_by_name['tflite'])
_TFLITEINFERENCECALCULATOROPTIONS_DELEGATE.fields_by_name['tflite'].containing_oneof = _TFLITEINFERENCECALCULATOROPTIONS_DELEGATE.oneofs_by_name['delegate']
_TFLITEINFERENCECALCULATOROPTIONS_DELEGATE.oneofs_by_name['delegate'].fields.append(
  _TFLITEINFERENCECALCULATOROPTIONS_DELEGATE.fields_by_name['gpu'])
_TFLITEINFERENCECALCULATOROPTIONS_DELEGATE.fields_by_name['gpu'].containing_oneof = _TFLITEINFERENCECALCULATOROPTIONS_DELEGATE.oneofs_by_name['delegate']
_TFLITEINFERENCECALCULATOROPTIONS_DELEGATE.oneofs_by_name['delegate'].fields.append(
  _TFLITEINFERENCECALCULATOROPTIONS_DELEGATE.fields_by_name['nnapi'])
_TFLITEINFERENCECALCULATOROPTIONS_DELEGATE.fields_by_name['nnapi'].containing_oneof = _TFLITEINFERENCECALCULATOROPTIONS_DELEGATE.oneofs_by_name['delegate']
_TFLITEINFERENCECALCULATOROPTIONS_DELEGATE.oneofs_by_name['delegate'].fields.append(
  _TFLITEINFERENCECALCULATOROPTIONS_DELEGATE.fields_by_name['xnnpack'])
_TFLITEINFERENCECALCULATOROPTIONS_DELEGATE.fields_by_name['xnnpack'].containing_oneof = _TFLITEINFERENCECALCULATOROPTIONS_DELEGATE.oneofs_by_name['delegate']
_TFLITEINFERENCECALCULATOROPTIONS.fields_by_name['delegate'].message_type = _TFLITEINFERENCECALCULATOROPTIONS_DELEGATE
DESCRIPTOR.message_types_by_name['TfLiteInferenceCalculatorOptions'] = _TFLITEINFERENCECALCULATOROPTIONS

TfLiteInferenceCalculatorOptions = _reflection.GeneratedProtocolMessageType('TfLiteInferenceCalculatorOptions', (_message.Message,), dict(

  Delegate = _reflection.GeneratedProtocolMessageType('Delegate', (_message.Message,), dict(

    TfLite = _reflection.GeneratedProtocolMessageType('TfLite', (_message.Message,), dict(
      DESCRIPTOR = _TFLITEINFERENCECALCULATOROPTIONS_DELEGATE_TFLITE,
      __module__ = 'mediapipe.calculators.tflite.tflite_inference_calculator_pb2'
      # @@protoc_insertion_point(class_scope:mediapipe.TfLiteInferenceCalculatorOptions.Delegate.TfLite)
      ))
    ,

    Gpu = _reflection.GeneratedProtocolMessageType('Gpu', (_message.Message,), dict(
      DESCRIPTOR = _TFLITEINFERENCECALCULATOROPTIONS_DELEGATE_GPU,
      __module__ = 'mediapipe.calculators.tflite.tflite_inference_calculator_pb2'
      # @@protoc_insertion_point(class_scope:mediapipe.TfLiteInferenceCalculatorOptions.Delegate.Gpu)
      ))
    ,

    Nnapi = _reflection.GeneratedProtocolMessageType('Nnapi', (_message.Message,), dict(
      DESCRIPTOR = _TFLITEINFERENCECALCULATOROPTIONS_DELEGATE_NNAPI,
      __module__ = 'mediapipe.calculators.tflite.tflite_inference_calculator_pb2'
      # @@protoc_insertion_point(class_scope:mediapipe.TfLiteInferenceCalculatorOptions.Delegate.Nnapi)
      ))
    ,

    Xnnpack = _reflection.GeneratedProtocolMessageType('Xnnpack', (_message.Message,), dict(
      DESCRIPTOR = _TFLITEINFERENCECALCULATOROPTIONS_DELEGATE_XNNPACK,
      __module__ = 'mediapipe.calculators.tflite.tflite_inference_calculator_pb2'
      # @@protoc_insertion_point(class_scope:mediapipe.TfLiteInferenceCalculatorOptions.Delegate.Xnnpack)
      ))
    ,
    DESCRIPTOR = _TFLITEINFERENCECALCULATOROPTIONS_DELEGATE,
    __module__ = 'mediapipe.calculators.tflite.tflite_inference_calculator_pb2'
    # @@protoc_insertion_point(class_scope:mediapipe.TfLiteInferenceCalculatorOptions.Delegate)
    ))
  ,
  DESCRIPTOR = _TFLITEINFERENCECALCULATOROPTIONS,
  __module__ = 'mediapipe.calculators.tflite.tflite_inference_calculator_pb2'
  # @@protoc_insertion_point(class_scope:mediapipe.TfLiteInferenceCalculatorOptions)
  ))
_sym_db.RegisterMessage(TfLiteInferenceCalculatorOptions)
_sym_db.RegisterMessage(TfLiteInferenceCalculatorOptions.Delegate)
_sym_db.RegisterMessage(TfLiteInferenceCalculatorOptions.Delegate.TfLite)
_sym_db.RegisterMessage(TfLiteInferenceCalculatorOptions.Delegate.Gpu)
_sym_db.RegisterMessage(TfLiteInferenceCalculatorOptions.Delegate.Nnapi)
_sym_db.RegisterMessage(TfLiteInferenceCalculatorOptions.Delegate.Xnnpack)

_TFLITEINFERENCECALCULATOROPTIONS.extensions_by_name['ext'].message_type = _TFLITEINFERENCECALCULATOROPTIONS
mediapipe_dot_framework_dot_calculator__options__pb2.CalculatorOptions.RegisterExtension(_TFLITEINFERENCECALCULATOROPTIONS.extensions_by_name['ext'])

_TFLITEINFERENCECALCULATOROPTIONS.fields_by_name['use_gpu'].has_options = True
_TFLITEINFERENCECALCULATOROPTIONS.fields_by_name['use_gpu']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\030\001'))
_TFLITEINFERENCECALCULATOROPTIONS.fields_by_name['use_nnapi'].has_options = True
_TFLITEINFERENCECALCULATOROPTIONS.fields_by_name['use_nnapi']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\030\001'))
# @@protoc_insertion_point(module_scope)
