# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mediapipe/calculators/util/landmarks_to_detection_calculator.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mediapipe.framework import calculator_pb2 as mediapipe_dot_framework_dot_calculator__pb2
mediapipe_dot_framework_dot_calculator__options__pb2 = mediapipe_dot_framework_dot_calculator__pb2.mediapipe_dot_framework_dot_calculator__options__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mediapipe/calculators/util/landmarks_to_detection_calculator.proto',
  package='mediapipe',
  syntax='proto2',
  serialized_pb=_b('\nBmediapipe/calculators/util/landmarks_to_detection_calculator.proto\x12\tmediapipe\x1a$mediapipe/framework/calculator.proto\"\xaa\x01\n%LandmarksToDetectionCalculatorOptions\x12!\n\x19selected_landmark_indices\x18\x01 \x03(\x05\x32^\n\x03\x65xt\x12\x1c.mediapipe.CalculatorOptions\x18\xf5\xa9\x89| \x01(\x0b\x32\x30.mediapipe.LandmarksToDetectionCalculatorOptions')
  ,
  dependencies=[mediapipe_dot_framework_dot_calculator__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_LANDMARKSTODETECTIONCALCULATOROPTIONS = _descriptor.Descriptor(
  name='LandmarksToDetectionCalculatorOptions',
  full_name='mediapipe.LandmarksToDetectionCalculatorOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='selected_landmark_indices', full_name='mediapipe.LandmarksToDetectionCalculatorOptions.selected_landmark_indices', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='ext', full_name='mediapipe.LandmarksToDetectionCalculatorOptions.ext', index=0,
      number=260199669, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=290,
)

DESCRIPTOR.message_types_by_name['LandmarksToDetectionCalculatorOptions'] = _LANDMARKSTODETECTIONCALCULATOROPTIONS

LandmarksToDetectionCalculatorOptions = _reflection.GeneratedProtocolMessageType('LandmarksToDetectionCalculatorOptions', (_message.Message,), dict(
  DESCRIPTOR = _LANDMARKSTODETECTIONCALCULATOROPTIONS,
  __module__ = 'mediapipe.calculators.util.landmarks_to_detection_calculator_pb2'
  # @@protoc_insertion_point(class_scope:mediapipe.LandmarksToDetectionCalculatorOptions)
  ))
_sym_db.RegisterMessage(LandmarksToDetectionCalculatorOptions)

_LANDMARKSTODETECTIONCALCULATOROPTIONS.extensions_by_name['ext'].message_type = _LANDMARKSTODETECTIONCALCULATOROPTIONS
mediapipe_dot_framework_dot_calculator__options__pb2.CalculatorOptions.RegisterExtension(_LANDMARKSTODETECTIONCALCULATOROPTIONS.extensions_by_name['ext'])

# @@protoc_insertion_point(module_scope)
