# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mediapipe/calculators/util/local_file_contents_calculator.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mediapipe.framework import calculator_pb2 as mediapipe_dot_framework_dot_calculator__pb2
mediapipe_dot_framework_dot_calculator__options__pb2 = mediapipe_dot_framework_dot_calculator__pb2.mediapipe_dot_framework_dot_calculator__options__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mediapipe/calculators/util/local_file_contents_calculator.proto',
  package='mediapipe',
  syntax='proto2',
  serialized_pb=_b('\n?mediapipe/calculators/util/local_file_contents_calculator.proto\x12\tmediapipe\x1a$mediapipe/framework/calculator.proto\"\x95\x01\n\"LocalFileContentsCalculatorOptions\x12\x11\n\ttext_mode\x18\x01 \x01(\x08\x32\\\n\x03\x65xt\x12\x1c.mediapipe.CalculatorOptions\x18\xbc\x80\xb2\xa5\x01 \x01(\x0b\x32-.mediapipe.LocalFileContentsCalculatorOptions')
  ,
  dependencies=[mediapipe_dot_framework_dot_calculator__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_LOCALFILECONTENTSCALCULATOROPTIONS = _descriptor.Descriptor(
  name='LocalFileContentsCalculatorOptions',
  full_name='mediapipe.LocalFileContentsCalculatorOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text_mode', full_name='mediapipe.LocalFileContentsCalculatorOptions.text_mode', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='ext', full_name='mediapipe.LocalFileContentsCalculatorOptions.ext', index=0,
      number=346849340, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=266,
)

DESCRIPTOR.message_types_by_name['LocalFileContentsCalculatorOptions'] = _LOCALFILECONTENTSCALCULATOROPTIONS

LocalFileContentsCalculatorOptions = _reflection.GeneratedProtocolMessageType('LocalFileContentsCalculatorOptions', (_message.Message,), dict(
  DESCRIPTOR = _LOCALFILECONTENTSCALCULATOROPTIONS,
  __module__ = 'mediapipe.calculators.util.local_file_contents_calculator_pb2'
  # @@protoc_insertion_point(class_scope:mediapipe.LocalFileContentsCalculatorOptions)
  ))
_sym_db.RegisterMessage(LocalFileContentsCalculatorOptions)

_LOCALFILECONTENTSCALCULATOROPTIONS.extensions_by_name['ext'].message_type = _LOCALFILECONTENTSCALCULATOROPTIONS
mediapipe_dot_framework_dot_calculator__options__pb2.CalculatorOptions.RegisterExtension(_LOCALFILECONTENTSCALCULATOROPTIONS.extensions_by_name['ext'])

# @@protoc_insertion_point(module_scope)
