# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mediapipe/calculators/util/detections_to_render_data_calculator.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mediapipe.framework import calculator_pb2 as mediapipe_dot_framework_dot_calculator__pb2
mediapipe_dot_framework_dot_calculator__options__pb2 = mediapipe_dot_framework_dot_calculator__pb2.mediapipe_dot_framework_dot_calculator__options__pb2
from mediapipe.util import color_pb2 as mediapipe_dot_util_dot_color__pb2
from mediapipe.util import render_data_pb2 as mediapipe_dot_util_dot_render__data__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mediapipe/calculators/util/detections_to_render_data_calculator.proto',
  package='mediapipe',
  syntax='proto2',
  serialized_pb=_b('\nEmediapipe/calculators/util/detections_to_render_data_calculator.proto\x12\tmediapipe\x1a$mediapipe/framework/calculator.proto\x1a\x1amediapipe/util/color.proto\x1a mediapipe/util/render_data.proto\"\x98\x03\n\'DetectionsToRenderDataCalculatorOptions\x12\"\n\x14produce_empty_packet\x18\x01 \x01(\x08:\x04true\x12\x19\n\x0etext_delimiter\x18\x02 \x01(\t:\x01,\x12!\n\x12one_label_per_line\x18\x03 \x01(\x08:\x05\x66\x61lse\x12.\n\x04text\x18\x04 \x01(\x0b\x32 .mediapipe.RenderAnnotation.Text\x12\x14\n\tthickness\x18\x05 \x01(\x01:\x01\x31\x12\x1f\n\x05\x63olor\x18\x06 \x01(\x0b\x32\x10.mediapipe.Color\x12\x1e\n\x0bscene_class\x18\x07 \x01(\t:\tDETECTION\x12\"\n\x13render_detection_id\x18\x08 \x01(\x08:\x05\x66\x61lse2`\n\x03\x65xt\x12\x1c.mediapipe.CalculatorOptions\x18\xe6\xde\xb6v \x01(\x0b\x32\x32.mediapipe.DetectionsToRenderDataCalculatorOptions')
  ,
  dependencies=[mediapipe_dot_framework_dot_calculator__pb2.DESCRIPTOR,mediapipe_dot_util_dot_color__pb2.DESCRIPTOR,mediapipe_dot_util_dot_render__data__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DETECTIONSTORENDERDATACALCULATOROPTIONS = _descriptor.Descriptor(
  name='DetectionsToRenderDataCalculatorOptions',
  full_name='mediapipe.DetectionsToRenderDataCalculatorOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='produce_empty_packet', full_name='mediapipe.DetectionsToRenderDataCalculatorOptions.produce_empty_packet', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='text_delimiter', full_name='mediapipe.DetectionsToRenderDataCalculatorOptions.text_delimiter', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b(",").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='one_label_per_line', full_name='mediapipe.DetectionsToRenderDataCalculatorOptions.one_label_per_line', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='text', full_name='mediapipe.DetectionsToRenderDataCalculatorOptions.text', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='thickness', full_name='mediapipe.DetectionsToRenderDataCalculatorOptions.thickness', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='color', full_name='mediapipe.DetectionsToRenderDataCalculatorOptions.color', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='scene_class', full_name='mediapipe.DetectionsToRenderDataCalculatorOptions.scene_class', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("DETECTION").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='render_detection_id', full_name='mediapipe.DetectionsToRenderDataCalculatorOptions.render_detection_id', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='ext', full_name='mediapipe.DetectionsToRenderDataCalculatorOptions.ext', index=0,
      number=248360806, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=185,
  serialized_end=593,
)

_DETECTIONSTORENDERDATACALCULATOROPTIONS.fields_by_name['text'].message_type = mediapipe_dot_util_dot_render__data__pb2._RENDERANNOTATION_TEXT
_DETECTIONSTORENDERDATACALCULATOROPTIONS.fields_by_name['color'].message_type = mediapipe_dot_util_dot_color__pb2._COLOR
DESCRIPTOR.message_types_by_name['DetectionsToRenderDataCalculatorOptions'] = _DETECTIONSTORENDERDATACALCULATOROPTIONS

DetectionsToRenderDataCalculatorOptions = _reflection.GeneratedProtocolMessageType('DetectionsToRenderDataCalculatorOptions', (_message.Message,), dict(
  DESCRIPTOR = _DETECTIONSTORENDERDATACALCULATOROPTIONS,
  __module__ = 'mediapipe.calculators.util.detections_to_render_data_calculator_pb2'
  # @@protoc_insertion_point(class_scope:mediapipe.DetectionsToRenderDataCalculatorOptions)
  ))
_sym_db.RegisterMessage(DetectionsToRenderDataCalculatorOptions)

_DETECTIONSTORENDERDATACALCULATOROPTIONS.extensions_by_name['ext'].message_type = _DETECTIONSTORENDERDATACALCULATOROPTIONS
mediapipe_dot_framework_dot_calculator__options__pb2.CalculatorOptions.RegisterExtension(_DETECTIONSTORENDERDATACALCULATOROPTIONS.extensions_by_name['ext'])

# @@protoc_insertion_point(module_scope)
