# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mediapipe/util/tracking/tone_models.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mediapipe/util/tracking/tone_models.proto',
  package='mediapipe',
  syntax='proto2',
  serialized_pb=_b('\n)mediapipe/util/tracking/tone_models.proto\x12\tmediapipe\"\x87\x01\n\rGainBiasModel\x12\x12\n\x07gain_c1\x18\x01 \x01(\x02:\x01\x31\x12\x12\n\x07\x62ias_c1\x18\x02 \x01(\x02:\x01\x30\x12\x12\n\x07gain_c2\x18\x03 \x01(\x02:\x01\x31\x12\x12\n\x07\x62ias_c2\x18\x04 \x01(\x02:\x01\x30\x12\x12\n\x07gain_c3\x18\x05 \x01(\x02:\x01\x31\x12\x12\n\x07\x62ias_c3\x18\x06 \x01(\x02:\x01\x30\"?\n\x14MixtureGainBiasModel\x12\'\n\x05model\x18\x01 \x03(\x0b\x32\x18.mediapipe.GainBiasModel\"\xdd\x01\n\x0f\x41\x66\x66ineToneModel\x12\x0f\n\x04g_00\x18\x01 \x01(\x02:\x01\x31\x12\x0f\n\x04g_01\x18\x02 \x01(\x02:\x01\x30\x12\x0f\n\x04g_02\x18\x03 \x01(\x02:\x01\x30\x12\x0f\n\x04g_03\x18\x04 \x01(\x02:\x01\x30\x12\x0f\n\x04g_10\x18\x05 \x01(\x02:\x01\x30\x12\x0f\n\x04g_11\x18\x06 \x01(\x02:\x01\x31\x12\x0f\n\x04g_12\x18\x07 \x01(\x02:\x01\x30\x12\x0f\n\x04g_13\x18\x08 \x01(\x02:\x01\x30\x12\x0f\n\x04g_20\x18\t \x01(\x02:\x01\x30\x12\x0f\n\x04g_21\x18\n \x01(\x02:\x01\x30\x12\x0f\n\x04g_22\x18\x0b \x01(\x02:\x01\x31\x12\x0f\n\x04g_23\x18\x0c \x01(\x02:\x01\x30\"C\n\x16MixtureAffineToneModel\x12)\n\x05model\x18\x01 \x03(\x0b\x32\x1a.mediapipe.AffineToneModel')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GAINBIASMODEL = _descriptor.Descriptor(
  name='GainBiasModel',
  full_name='mediapipe.GainBiasModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gain_c1', full_name='mediapipe.GainBiasModel.gain_c1', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bias_c1', full_name='mediapipe.GainBiasModel.bias_c1', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gain_c2', full_name='mediapipe.GainBiasModel.gain_c2', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bias_c2', full_name='mediapipe.GainBiasModel.bias_c2', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gain_c3', full_name='mediapipe.GainBiasModel.gain_c3', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bias_c3', full_name='mediapipe.GainBiasModel.bias_c3', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=192,
)


_MIXTUREGAINBIASMODEL = _descriptor.Descriptor(
  name='MixtureGainBiasModel',
  full_name='mediapipe.MixtureGainBiasModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model', full_name='mediapipe.MixtureGainBiasModel.model', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=194,
  serialized_end=257,
)


_AFFINETONEMODEL = _descriptor.Descriptor(
  name='AffineToneModel',
  full_name='mediapipe.AffineToneModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='g_00', full_name='mediapipe.AffineToneModel.g_00', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='g_01', full_name='mediapipe.AffineToneModel.g_01', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='g_02', full_name='mediapipe.AffineToneModel.g_02', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='g_03', full_name='mediapipe.AffineToneModel.g_03', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='g_10', full_name='mediapipe.AffineToneModel.g_10', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='g_11', full_name='mediapipe.AffineToneModel.g_11', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='g_12', full_name='mediapipe.AffineToneModel.g_12', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='g_13', full_name='mediapipe.AffineToneModel.g_13', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='g_20', full_name='mediapipe.AffineToneModel.g_20', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='g_21', full_name='mediapipe.AffineToneModel.g_21', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='g_22', full_name='mediapipe.AffineToneModel.g_22', index=10,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='g_23', full_name='mediapipe.AffineToneModel.g_23', index=11,
      number=12, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=260,
  serialized_end=481,
)


_MIXTUREAFFINETONEMODEL = _descriptor.Descriptor(
  name='MixtureAffineToneModel',
  full_name='mediapipe.MixtureAffineToneModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model', full_name='mediapipe.MixtureAffineToneModel.model', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=483,
  serialized_end=550,
)

_MIXTUREGAINBIASMODEL.fields_by_name['model'].message_type = _GAINBIASMODEL
_MIXTUREAFFINETONEMODEL.fields_by_name['model'].message_type = _AFFINETONEMODEL
DESCRIPTOR.message_types_by_name['GainBiasModel'] = _GAINBIASMODEL
DESCRIPTOR.message_types_by_name['MixtureGainBiasModel'] = _MIXTUREGAINBIASMODEL
DESCRIPTOR.message_types_by_name['AffineToneModel'] = _AFFINETONEMODEL
DESCRIPTOR.message_types_by_name['MixtureAffineToneModel'] = _MIXTUREAFFINETONEMODEL

GainBiasModel = _reflection.GeneratedProtocolMessageType('GainBiasModel', (_message.Message,), dict(
  DESCRIPTOR = _GAINBIASMODEL,
  __module__ = 'mediapipe.util.tracking.tone_models_pb2'
  # @@protoc_insertion_point(class_scope:mediapipe.GainBiasModel)
  ))
_sym_db.RegisterMessage(GainBiasModel)

MixtureGainBiasModel = _reflection.GeneratedProtocolMessageType('MixtureGainBiasModel', (_message.Message,), dict(
  DESCRIPTOR = _MIXTUREGAINBIASMODEL,
  __module__ = 'mediapipe.util.tracking.tone_models_pb2'
  # @@protoc_insertion_point(class_scope:mediapipe.MixtureGainBiasModel)
  ))
_sym_db.RegisterMessage(MixtureGainBiasModel)

AffineToneModel = _reflection.GeneratedProtocolMessageType('AffineToneModel', (_message.Message,), dict(
  DESCRIPTOR = _AFFINETONEMODEL,
  __module__ = 'mediapipe.util.tracking.tone_models_pb2'
  # @@protoc_insertion_point(class_scope:mediapipe.AffineToneModel)
  ))
_sym_db.RegisterMessage(AffineToneModel)

MixtureAffineToneModel = _reflection.GeneratedProtocolMessageType('MixtureAffineToneModel', (_message.Message,), dict(
  DESCRIPTOR = _MIXTUREAFFINETONEMODEL,
  __module__ = 'mediapipe.util.tracking.tone_models_pb2'
  # @@protoc_insertion_point(class_scope:mediapipe.MixtureAffineToneModel)
  ))
_sym_db.RegisterMessage(MixtureAffineToneModel)


# @@protoc_insertion_point(module_scope)
