# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mediapipe/gpu/copy_calculator.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mediapipe.framework import calculator_pb2 as mediapipe_dot_framework_dot_calculator__pb2
mediapipe_dot_framework_dot_calculator__options__pb2 = mediapipe_dot_framework_dot_calculator__pb2.mediapipe_dot_framework_dot_calculator__options__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mediapipe/gpu/copy_calculator.proto',
  package='mediapipe',
  syntax='proto2',
  serialized_pb=_b('\n#mediapipe/gpu/copy_calculator.proto\x12\tmediapipe\x1a$mediapipe/framework/calculator.proto\"\xd7\x01\n\x15\x43opyCalculatorOptions\x12\x41\n\x08rotation\x18\x01 \x01(\x0e\x32).mediapipe.CopyCalculatorOptions.Rotation:\x04NONE\"+\n\x08Rotation\x12\x08\n\x04NONE\x10\x00\x12\x07\n\x03\x43\x43W\x10\x01\x12\x0c\n\x08\x43\x43W_FLIP\x10\x02\x32N\n\x03\x65xt\x12\x1c.mediapipe.CalculatorOptions\x18\xb4\xf2\x91M \x01(\x0b\x32 .mediapipe.CopyCalculatorOptions')
  ,
  dependencies=[mediapipe_dot_framework_dot_calculator__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_COPYCALCULATOROPTIONS_ROTATION = _descriptor.EnumDescriptor(
  name='Rotation',
  full_name='mediapipe.CopyCalculatorOptions.Rotation',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CCW', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CCW_FLIP', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=181,
  serialized_end=224,
)
_sym_db.RegisterEnumDescriptor(_COPYCALCULATOROPTIONS_ROTATION)


_COPYCALCULATOROPTIONS = _descriptor.Descriptor(
  name='CopyCalculatorOptions',
  full_name='mediapipe.CopyCalculatorOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rotation', full_name='mediapipe.CopyCalculatorOptions.rotation', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='ext', full_name='mediapipe.CopyCalculatorOptions.ext', index=0,
      number=161773876, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[],
  enum_types=[
    _COPYCALCULATOROPTIONS_ROTATION,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=304,
)

_COPYCALCULATOROPTIONS.fields_by_name['rotation'].enum_type = _COPYCALCULATOROPTIONS_ROTATION
_COPYCALCULATOROPTIONS_ROTATION.containing_type = _COPYCALCULATOROPTIONS
DESCRIPTOR.message_types_by_name['CopyCalculatorOptions'] = _COPYCALCULATOROPTIONS

CopyCalculatorOptions = _reflection.GeneratedProtocolMessageType('CopyCalculatorOptions', (_message.Message,), dict(
  DESCRIPTOR = _COPYCALCULATOROPTIONS,
  __module__ = 'mediapipe.gpu.copy_calculator_pb2'
  # @@protoc_insertion_point(class_scope:mediapipe.CopyCalculatorOptions)
  ))
_sym_db.RegisterMessage(CopyCalculatorOptions)

_COPYCALCULATOROPTIONS.extensions_by_name['ext'].message_type = _COPYCALCULATOROPTIONS
mediapipe_dot_framework_dot_calculator__options__pb2.CalculatorOptions.RegisterExtension(_COPYCALCULATOROPTIONS.extensions_by_name['ext'])

# @@protoc_insertion_point(module_scope)
